package com.ssomar.minecraftmarketplacesapi;

import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.time.Duration;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class PolymartBrowser extends VirtualBrowser {

    public static final String BASE = "https://polymart.org/";

    private final String loggedInUserId;

    private int t;

    public PolymartBrowser(String dataDir, String polymardUsername, String polymartPassword) throws Exception{
        super(BASE, dataDir + "2", false);
        t = 0;
        System.out.println("Try to connect on polymart with the username: " + polymardUsername);
        loggedInUserId = login(polymardUsername, polymartPassword);
    }

    private String login(String username, String password) throws Exception {

        if (t == 4) {
            throw new Exception("Error while login to : " + BASE + " with the username: " + username);
        }
        try {
            navigate(BASE + "/login");
            sleep(3000);

            // Wait for Cloudflare if present
            waitForCloudflare(15);

            // Check if already logged in (redirected away from login page)
            if (!driver.getCurrentUrl().contains("/login")) {
                System.out.println("Already logged in (redirected to: " + driver.getCurrentUrl() + ")");
                String userId = extractUserId(driver);
                if (userId != null && !userId.equals("username non retrouvé")) {
                    System.out.println("User ID: " + userId);
                    return userId;
                }
            }

            JavascriptExecutor js = (JavascriptExecutor) driver;

            // Wait for the login form to be ready (generated by makeForm JS)
            WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(15));
            wait.until(ExpectedConditions.presenceOfElementLocated(By.name("email")));
            wait.until(ExpectedConditions.presenceOfElementLocated(By.name("password")));

            // Polymart uses a double-submit CSRF pattern:
            // 1st submit establishes the csrf cookie
            // 2nd submit validates credentials against that cookie
            // This is why even manual login requires clicking Login twice.

            for (int attempt = 1; attempt <= 2; attempt++) {
                // Set field values via JavaScript
                js.executeScript(
                    "var emailInput = document.querySelector('input[name=\"email\"]');" +
                    "var passwordInput = document.querySelector('input[name=\"password\"]');" +
                    "if (emailInput) {" +
                    "  emailInput.value = arguments[0];" +
                    "  emailInput.dispatchEvent(new Event('input', {bubbles: true}));" +
                    "  emailInput.dispatchEvent(new Event('change', {bubbles: true}));" +
                    "}" +
                    "if (passwordInput) {" +
                    "  passwordInput.value = arguments[1];" +
                    "  passwordInput.dispatchEvent(new Event('input', {bubbles: true}));" +
                    "  passwordInput.dispatchEvent(new Event('change', {bubbles: true}));" +
                    "}",
                    username, password
                );

                // Check the "Remember me" checkbox
                js.executeScript(
                    "var checkbox = document.querySelector('input[name=\"remember\"]');" +
                    "if (checkbox && !checkbox.checked) checkbox.click();"
                );

                sleep(1000);

                // Submit using doco.js's submitForm function
                Object submitResult = js.executeScript(
                    "if (typeof submitForm === 'function') {" +
                    "  try { submitForm('login'); return 'submitForm called'; }" +
                    "  catch(e) { return 'submitForm error: ' + e.message; }" +
                    "} else {" +
                    "  var btn = document.getElementById('login-4');" +
                    "  if (btn) { btn.click(); return 'button clicked'; }" +
                    "  var form = document.getElementById('login');" +
                    "  if (form) { form.submit(); return 'form submitted'; }" +
                    "  return 'no form found';" +
                    "}"
                );
                System.out.println("[Polymart] Login submit #" + attempt + ": " + submitResult);

                sleep(8000);
                waitForCloudflare(15);

                // Check if login succeeded (redirected away from login page)
                if (!driver.getCurrentUrl().contains("/login")) {
                    System.out.println("[Polymart] Login successful after submit #" + attempt);
                    break;
                }

                if (attempt == 1) {
                    System.out.println("[Polymart] First submit established CSRF cookie, retrying...");
                    // Wait for new form to load before second attempt
                    wait.until(ExpectedConditions.presenceOfElementLocated(By.name("email")));
                } else {
                    // Second attempt also failed - check for errors
                    Object errors = js.executeScript(
                        "var msgs = [];" +
                        "var respEls = document.querySelectorAll('.response-message');" +
                        "for (var i = 0; i < respEls.length; i++) {" +
                        "  var text = respEls[i].textContent.trim();" +
                        "  if (text) msgs.push(text);" +
                        "}" +
                        "return msgs.length > 0 ? msgs.join(' | ') : 'no error messages found';"
                    );
                    System.err.println("[Polymart] Login failed after 2 submits. Errors: " + errors);
                }
            }

            String userId = extractUserId(driver);

            if (userId != null && !userId.equals("username non retrouvé")) {
                System.out.println("User ID: " + userId);
            } else {
                System.out.println("Could not extract user ID, current URL: " + driver.getCurrentUrl());
            }
            return userId;

        } catch (Exception | Error e) {
            e.printStackTrace();
            System.out.println("Error while login Polymart, try again in 15 seconds (attempt " + (t+1) + "/4)");
            sleep(15000);
            t++;
            return login(username, password);
        }
    }

    /**
     * Wait for Cloudflare challenge to resolve, up to maxWaitSeconds.
     */
    private void waitForCloudflare(int maxWaitSeconds) {
        for (int i = 0; i < maxWaitSeconds; i++) {
            if (!isCloudflare()) return;
            if (i == 0) System.out.println("[Polymart] Waiting for Cloudflare challenge...");
            sleep(1000);
        }
        if (isCloudflare()) {
            System.err.println("[Polymart] WARNING: Cloudflare challenge still present after " + maxWaitSeconds + "s");
        }
    }

    public String extractUserId(ChromeDriver driver) {

        try {
            // Strategy 1: profile photo link
            WebElement link = driver.findElement(By.xpath("//a[.//img[contains(@alt, 'profile photo') or contains(@alt, 'Profile') or contains(@alt, 'avatar')]]"));
            String href = link.getAttribute("href");
            Pattern pattern = Pattern.compile("/user/(\\d+)");
            Matcher matcher = pattern.matcher(href);
            if (matcher.find()) {
                return matcher.group(1);
            }
        } catch (Exception e) {
            // Try strategy 2: look for any /user/{id} link in the header/nav
            try {
                List<WebElement> links = driver.findElements(By.xpath("//a[contains(@href, '/user/')]"));
                for (WebElement l : links) {
                    String href = l.getAttribute("href");
                    Pattern pattern = Pattern.compile("/user/(\\d+)");
                    Matcher matcher = pattern.matcher(href);
                    if (matcher.find()) {
                        return matcher.group(1);
                    }
                }
            } catch (Exception e2) {
                // ignore
            }
        }

        return "username non retrouvé";
    }

    public BuyerResp addBuyer(String ressourceID, String buyerUsername) {

        try {
            navigate(BASE + "/resource/" + ressourceID + "/buyers");
            sleep(2000);
            waitForCloudflare(15);
            if (isCloudflare()) return BuyerResp.SYSTEM_ERROR;
            sleep(2000);
            WebElement addBuyer = driver.findElement(By.id("product-buyers"));
            WebElement addBuyerButton = addBuyer.findElement(By.id("buyer-option-buttons"));
            WebElement addBuyerButton2 = addBuyerButton.findElements(By.tagName("a")).get(2);
            addBuyerButton2.click();
            sleep(1000);
            WebElement buyerName = driver.findElement(By.name("buyer_user"));
            buyerName.sendKeys(buyerUsername);
            sleep(1000);
            WebElement addBuyer2 = driver.findElement(By.xpath("//input[contains(@value, 'Add Buyer')]"));
            addBuyer2.submit();
            sleep(1000);
            if (driver.getPageSource().contains("The requested user could not be found.")) {
                System.out.println("[INFO] USER: " + buyerUsername + " NOT FOUND and can't be added in the buyer list of " + ressourceID);
                return BuyerResp.INVALID_SPIGOT_USERNAME;
            } else {
                System.out.println("[INFO] USER: " + buyerUsername + " added in the buyer list of the resource: " + ressourceID);
                return BuyerResp.VALID;
            }
        } catch (Exception e) {
            e.printStackTrace();
            return BuyerResp.SYSTEM_ERROR;
        }
    }

    public String getUsername(String polymartID) {

        try {
            navigate(BASE + "/user/" + polymartID);
            sleep(1000);
            String link = driver.getCurrentUrl();

            return link.split("\\/")[4].split("\\.")[0];
        } catch (Exception e) {
            e.printStackTrace();
            return "Ssomar";
        }
    }

    public void postAnUpdate(String link, String version, String title, String description, String uploadFilePath) {
        try {
            navigate(BASE + link);
            sleep(3000);

            // Wait for Cloudflare
            waitForCloudflare(15);

            JavascriptExecutor js = (JavascriptExecutor) driver;
            WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(15));

            // Find "Post an update" link - try multiple strategies
            WebElement updateElem = null;
            // Strategy 1: exact text match
            try { updateElem = driver.findElement(By.xpath("//a[text()='Post an update']")); } catch (Exception ignored) {}
            // Strategy 2: case-insensitive partial text match
            if (updateElem == null) {
                try { updateElem = driver.findElement(By.xpath("//a[contains(translate(text(),'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz'),'post an update')]")); } catch (Exception ignored) {}
            }
            // Strategy 3: look for link containing "update" in href with post-like text
            if (updateElem == null) {
                try { updateElem = driver.findElement(By.xpath("//a[contains(translate(text(),'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz'),'post') and contains(translate(text(),'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz'),'update')]")); } catch (Exception ignored) {}
            }
            // Strategy 4: button instead of link
            if (updateElem == null) {
                try { updateElem = driver.findElement(By.xpath("//button[contains(translate(text(),'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz'),'post') and contains(translate(text(),'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz'),'update')]")); } catch (Exception ignored) {}
            }

            if (updateElem == null) {
                System.err.println("[Polymart] Could not find 'Post an update' link. URL: " + driver.getCurrentUrl());
                System.err.println("[Polymart] Page title: " + driver.getTitle());
                // Log all links on page for debugging
                List<WebElement> allLinks = driver.findElements(By.tagName("a"));
                System.err.println("[Polymart] Links found on page (" + allLinks.size() + "):");
                for (WebElement a : allLinks) {
                    String text = a.getText().trim();
                    if (!text.isEmpty() && text.length() < 80) {
                        System.err.println("  - \"" + text + "\" -> " + a.getAttribute("href"));
                    }
                }
                return;
            }

            updateElem.click();
            sleep(2000);

            // Wait for Cloudflare after navigation
            waitForCloudflare(10);

            // Fill version field by name
            WebElement versionElem = wait.until(ExpectedConditions.elementToBeClickable(By.name("version")));
            versionElem.clear();
            versionElem.sendKeys(version);
            sleep(1000);

            // Fill title field by name
            WebElement titleElem = wait.until(ExpectedConditions.elementToBeClickable(By.name("update_title")));
            titleElem.clear();
            titleElem.sendKeys(title);
            sleep(1000);

            // Fill description via TinyMCE iframe - find it dynamically
            sleep(1000);
            boolean descriptionFilled = false;

            // Strategy 1: find TinyMCE iframe by ID pattern (_ifr suffix)
            List<WebElement> iframes = driver.findElements(By.cssSelector("iframe[id$='_ifr']"));
            if (!iframes.isEmpty()) {
                WebElement tinymceIframe = iframes.get(0);
                System.out.println("[Polymart] Found TinyMCE iframe: " + tinymceIframe.getAttribute("id"));
                driver.switchTo().frame(tinymceIframe);
                WebElement body = driver.findElement(By.tagName("body"));
                body.clear();
                body.sendKeys(stripBBCode(description));
                driver.switchTo().defaultContent();
                descriptionFilled = true;
            }

            // Strategy 2: try the old hardcoded ID
            if (!descriptionFilled) {
                try {
                    driver.switchTo().frame("_general-form-1-3_ifr");
                    WebElement body = driver.findElement(By.tagName("body"));
                    body.clear();
                    body.sendKeys(stripBBCode(description));
                    driver.switchTo().defaultContent();
                    descriptionFilled = true;
                } catch (Exception e) {
                    driver.switchTo().defaultContent();
                }
            }

            // Strategy 3: try to find a textarea by name as fallback
            if (!descriptionFilled) {
                try {
                    WebElement textarea = driver.findElement(By.name("update_description"));
                    textarea.clear();
                    textarea.sendKeys(stripBBCode(description));
                    descriptionFilled = true;
                } catch (Exception ignored) {}
            }

            // Strategy 4: use JavaScript to set TinyMCE content
            if (!descriptionFilled) {
                try {
                    js.executeScript(
                        "if(typeof tinymce !== 'undefined' && tinymce.editors.length > 0) { " +
                        "  tinymce.editors[0].setContent(arguments[0]); " +
                        "  return true; " +
                        "} return false;",
                        stripBBCode(description)
                    );
                    descriptionFilled = true;
                    System.out.println("[Polymart] Set description via TinyMCE JS API");
                } catch (Exception e) {
                    System.err.println("[Polymart] WARNING: Could not fill description field: " + e.getMessage());
                }
            }

            sleep(2000);

            // Upload file by name
            WebElement uploadElem = driver.findElement(By.name("update_file"));
            uploadElem.sendKeys(uploadFilePath);
            sleep(7000);

            // Find and click submit button - try multiple strategies
            WebElement submitButton = null;

            // Strategy 1: old hardcoded ID
            try { submitButton = driver.findElement(By.id("_general-form-1-9")); } catch (Exception ignored) {}

            // Strategy 2: find submit input/button by type
            if (submitButton == null) {
                try {
                    List<WebElement> submits = driver.findElements(By.cssSelector("input[type='submit'], button[type='submit']"));
                    // Pick the last submit button on the page (likely the form submit, not any other)
                    if (!submits.isEmpty()) {
                        submitButton = submits.get(submits.size() - 1);
                    }
                } catch (Exception ignored) {}
            }

            // Strategy 3: find by value text
            if (submitButton == null) {
                try { submitButton = driver.findElement(By.xpath("//input[contains(@value,'Post') or contains(@value,'Submit') or contains(@value,'Update')]")); } catch (Exception ignored) {}
            }

            // Strategy 4: find button with post/submit text
            if (submitButton == null) {
                try { submitButton = driver.findElement(By.xpath("//button[contains(text(),'Post') or contains(text(),'Submit') or contains(text(),'Update')]")); } catch (Exception ignored) {}
            }

            if (submitButton != null) {
                System.out.println("[Polymart] Clicking submit button: tag=" + submitButton.getTagName() + ", id=" + submitButton.getAttribute("id") + ", value=" + submitButton.getAttribute("value"));
                // Use JavaScript click to trigger the onclick handler properly
                js.executeScript("arguments[0].click();", submitButton);
                sleep(10000);
                System.out.println("[Polymart] Update posted. Current URL: " + driver.getCurrentUrl());
            } else {
                // Try to use submitForm directly as a last resort
                Object result = js.executeScript(
                    "var forms = Object.keys(typeof formInfo !== 'undefined' ? formInfo : {});" +
                    "for (var i = 0; i < forms.length; i++) {" +
                    "  if (forms[i] !== 'login' && document.getElementById(forms[i])) {" +
                    "    try { submitForm(forms[i]); return 'submitted: ' + forms[i]; } catch(e) { return 'error: ' + e.message; }" +
                    "  }" +
                    "}" +
                    "return 'no form found';"
                );
                System.out.println("[Polymart] Fallback submit result: " + result);
                sleep(10000);
            }
        } catch (Exception e) {
            System.err.println("[Polymart] Error posting update for link: " + link);
            System.err.println("[Polymart] Current URL: " + driver.getCurrentUrl());
            System.err.println("[Polymart] Page title: " + driver.getTitle());
            e.printStackTrace();
        }
    }

    public static String stripBBCode(String input) {
        String result = input;

        // Remove all [TAG] and [/TAG] patterns including ones with attributes like [URL='...']
        result = result.replaceAll("(?i)\\[(\\/)?[a-z]+(=[^\\]]+)?\\]", "");

        // Replace multiple blank lines with just 2 newlines
        result = result.replaceAll("\\n{3,}", "\n\n");

        // Trim whitespace
        return result.trim();
    }

    public static String convertToMarkdown(String input) {
        String result = input;

        // Convert [IMG]...[/IMG] to Markdown image
        result = result.replaceAll("(?i)\\[IMG\\](.*?)\\[/IMG\\]", "![]($1)");

        // Convert [URL='...']...[/URL] to Markdown link
        result = result.replaceAll("(?i)\\[URL='(.*?)'\\](.*?)\\[/URL\\]", "[$2]($1)");

        // Remove formatting tags: [B], [I], [SIZE=...], [COLOR=...], [CENTER], etc.
        result = result.replaceAll("(?i)\\[/?(B|I|U|CENTER|SIZE=\\d+|SIZE|COLOR=#[0-9A-Fa-f]{6}|COLOR=rgb\\([^\\]]+\\)|COLOR)\\]", "");

        // Convert multiple newlines into maximum 2 (to avoid too many line breaks)
        result = result.replaceAll("\\n{3,}", "\n\n");

        // Trim leading/trailing whitespace
        return result.trim();
    }


    private String parseAvatarUrl(String url) {
        if (url.startsWith("data")) return BASE + "/" + url;
        if (url.startsWith("//static")) return "https:" + url;
        return url;
    }
}
